#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/tmc-deploy/tmc_deploy.rb'

require './site.rb'

WORK_DIR = File.realpath(File.dirname(__FILE__)) + '/work'
STAGING_DIR = WORK_DIR + '/staging'
PLUGIN_REPO = 'git://github.com/testmycode/tmc-netbeans.git'

FileUtils.rm_rf(WORK_DIR)
FileUtils.mkdir_p(WORK_DIR)
FileUtils.rm_rf(STAGING_DIR)
FileUtils.mkdir_p(STAGING_DIR)

def standard_deployment(deployment_name, version, tailoring_file)
  TmcDeploy.deployment(deployment_name, :work_dir => WORK_DIR) do |name|
      repo = git_clone(name, PLUGIN_REPO)
      repo.fetch('origin').reset_hard(version).clean
      build_tmc_nb_plugin(name,
          :tailoring_file => "../tailoring/#{tailoring_file}",
          :version => version,
          :netbeans_dir => NB_DIR,
          :nbplatform_name => 'nb721',
          :zip => true,
          :installers => true,
          :pack200 => true
      )
      stage_nb_plugin(name, STAGING_DIR)
      FileUtils.mkdir_p(UPDATE_SITE + '/' + name)
      move_dir_over(STAGING_DIR + '/updates', UPDATE_SITE + '/' + name)
  end
end

standard_deployment('tmc-netbeans', '0.3.13', 'GenericTailoring.java')
standard_deployment('tmc-netbeans_hy', '0.3.12', 'HyTailoring.java')
standard_deployment('tmc-netbeans_mooc', '0.3.13', 'MoocTailoring.java')
standard_deployment('tmc-netbeans_pk', '0.3.13', 'PkTailoring.java')

TmcDeploy.main(ARGV)
